image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - scala-lang.scala@0.3.9:kklqw+c/dNRmtTU8B5repw==
    - scalameta.metals@1.9.0:PtE/gdeE1YPL6It4tEfqpg==

tasks:
  - init: "mkdir -p .vscode && echo '{\"metals.sbtScript\": \"/home/gitpod/.local/share/coursier/bin/sbt\"}' > .vscode/settings.json"
  - command: for dir in .cache .config .local; do if test -d /home/gitpod/$dir; then if test -d /workspace/$dir; then rm -rf /home/gitpod/$dir; else mv /home/gitpod/$dir /workspace; fi; fi && if test -d /workspace/$dir; then ln -s /workspace/$dir /home/gitpod/; fi; done

ports:
  - port: 8212
    onOpen: ignore
