#!/bin/bash
set -ev

# On Travis, this leaves more memory to the forked JVM where tests are run
export SBT_OPTS="-J-Xmx512m -J-Xms512m"
SBT="sbt ++${TRAVIS_SCALA_VERSION:-2.10.5}"

# Temporary disabled: AutocompleteTests nbtest.NbTest
for TEST in AdvancedTests EulerTests EvaluatorTests FailureTests SerializationTests; do
  $SBT "kernel/test-only jupyter.scala.$TEST"
done

# Disabling Spark tests (even local ones) for lack of memory
if [ "$TRAVIS_SCALA_VERSION" = "" ]; then
  # $SBT "kernel/test-only jupyter.scala.LocalSpark12Tests"
  $SBT "kernel/test-only jupyter.scala.LocalSpark12Tests"
  $SBT "kernel/test-only jupyter.scala.LocalSpark13Tests"
fi

